name = input("Enter your name: ")
age = int(input("Enter your age: "))
city = input("Enter your city name: ")
course = input("Enter your course: ")
college = input("Enter your college name: ")
percentage = float(input("Enter your percentage: "))
grade = input("Enter your final result: ")

print("Name:", name)
print("Age:", age)
print("City:", city)
print("Course:", course)
print("College:", college)
print("Percentage:", percentage)
print("Grade:", grade)